# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.2.dev11+g7ea82d8.d20230221'
__version_tuple__ = version_tuple = (0, 4, 2, 'dev11', 'g7ea82d8.d20230221')
