# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.2.dev1+gb4e8070.d20230202'
__version_tuple__ = version_tuple = (0, 4, 2, 'dev1', 'gb4e8070.d20230202')
